INSERT INTO School VALUES (NULL, 'Vanoni, Morbegno Istituto Comprensivo', 0)  ;
INSERT INTO School VALUES (NULL, 'Damiani, Morbegno Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Talamona Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Ardenno Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Traona Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Delebio Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Aprica Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Campodolcino Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Cepina Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Berbenno Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Dubino Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Paesi Orobici, Sondrio Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Paesi Retici, Sondrio Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Bertacchi, Chiavenna Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Garibaldi, Chiavenna Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Ligari, Sondrio Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Gordona Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Isolaccia Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Trombini, Tirano Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Bormio Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Novate Mezzola Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Regoledo di Cosio Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Albosaggia Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Tresenda Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Villa di Tirano Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Grosio Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Grosotto Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Sondalo Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Sondrio, Maria Cecilia Turchi Istituto Comprensivo', 0);
INSERT INTO School VALUES (NULL, 'Chiesa Valmalenco Istituto Comprensivo', 0);

INSERT INTO School VALUES (NULL, 'Liceo P. Nervi - G. Ferrari, Morbegno', 1);
INSERT INTO School VALUES (NULL, 'Istituto Superiore P. Saraceno e G. P. Romegialli, Morbegno', 1);
INSERT INTO School VALUES (NULL, 'ENAIP, Morbegno', 1);
INSERT INTO School VALUES (NULL, 'Liceo G. Piazzi - C. Lena Perpenti, Sondrio', 1);
INSERT INTO School VALUES (NULL, 'Liceo Scientifico Donegani, Sondrio', 1);
INSERT INTO School VALUES (NULL, 'Istituto Tecnico A. De Simoni - M. Quadrio, Sondrio', 1);
INSERT INTO School VALUES (NULL, 'ITI E. Mattei, Sondrio', 1);
INSERT INTO School VALUES (NULL, 'Istituto Superiore Besta e Fossati, Sondrio', 1);
INSERT INTO School VALUES (NULL, 'Istituto Pio XII, Sondrio', 1);
INSERT INTO School VALUES (NULL, 'APF, Sondrio', 1);
INSERT INTO School VALUES (NULL, 'Istituto Tecnico A. De Simoni - M. Quadrio, Sondrio', 1);
INSERT INTO School VALUES (NULL, 'Istituto di Istruzione Superiore Alberti, Bormio', 1);
INSERT INTO School VALUES (NULL, 'APF, Sondalo', 1);
INSERT INTO School VALUES (NULL, 'Istituto di Istruzione Superiore Leonardo da Vinci, Chiavenna', 1);
INSERT INTO School VALUES (NULL, 'Istituto Professionale Alberghiero Crotto Caurga, Chiavenna', 1);
INSERT INTO School VALUES (NULL, 'Istituto di Istruzione Superiore Balilla Pinchetti, Tirano', 1);

INSERT INTO Period VALUES (NULL, '1 Luglio dalle 9.30 alle 12.00');
INSERT INTO Period VALUES (NULL, '2 Luglio dalle 14.30 alle 17.30');
INSERT INTO Period VALUES (NULL, '3 Luglio dalle 9.30 alle 12.00');
INSERT INTO Period VALUES (NULL, '4 Luglio dalle 14.30 alle 17.30');
INSERT INTO Period VALUES (NULL, '7 Luglio dalle 14.30 alle 17.30');
INSERT INTO Period VALUES (NULL, '8 Luglio dalle 9.30 alle 12.00');
INSERT INTO Period VALUES (NULL, '9 Luglio dalle 14.30 alle 17.30');
INSERT INTO Period VALUES (NULL, '10 Luglio dalle 9.30 alle 12.00');
INSERT INTO Period VALUES (NULL, '11 Luglio dalle 14.30 alle 17.30');
INSERT INTO Period VALUES (NULL, '14 Luglio dalle 14.30 alle 17.30');
INSERT INTO Period VALUES (NULL, '15 Luglio dalle 9.30 alle 12.00');
INSERT INTO Period VALUES (NULL, '16 Luglio dalle 14.30 alle 17.30');
INSERT INTO Period VALUES (NULL, '17 Luglio dalle 9.30 alle 12.00');
INSERT INTO Period VALUES (NULL, '18 Luglio dalle 14.30 alle 17.30');